user  nginx;
worker_processes  auto;
error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;

    server {
        listen               80 default_server;
        listen               [::]:80 default_server;
        server_name          _;

        # 【智能分流逻辑】
        location / {
            # 1. 如果检测到是客户端（带有 Upgrade: websocket）
            if ($http_upgrade = "websocket") {
                proxy_pass http://[::1]:8880;
            }

            # 2. 如果是浏览器（普通 GET 请求），显示网页
            root /usr/share/nginx/html;
            index index.html;

            # 基础转发头
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $http_host;
            # 增加这三行，确保双栈下的真实 IP 传递
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # V2Ray 路径保持不变
        location VMESS_WSPATH {
            proxy_pass http://127.0.0.1:10000;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $http_host;
        }

        location VLESS_WSPATH {
            proxy_pass http://127.0.0.1:20000;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $http_host;
        }
    }
}
